---
# handlers file for ad_auth

- name: Restart realmd service
  ansible.builtin.systemd:
    name: realmd
    state: restarted
  when:
    - not ansible_check_mode | bool

- name: Restart sssd service
  ansible.builtin.systemd:
    name: sssd
    state: restarted
  when:
    - ad_auth_join | bool
    - not ansible_check_mode | bool
